name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: List before checkout
        run: ls -l

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: List after checkout
        run: ls -l

      - name: Greet the User
        env:
          MY_ENV: "Learning GitHub Actions"
        run: |
          echo "Hello World!"
          echo "Custom variable: $MY_ENV"
          echo "Actor: $GITHUB_ACTOR"
